config/routes.rb
Main::Application.routes.draw do
  resources :problemas
  resources :manoobras
  resources :metodos
  resources :maquinas
  resources :materials
  resources :medicions
  resources :medioambientes
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :proyects, only: [:create, :destroy]
  resources "contacts", only: [:new, :create]
  root 'static_pages#home'
  match '/seism', to: 'variables_entrada#seism', via: 'get'

  match '/openii_proyect', to: 'proyects#openii_proyect', via: 'get'
  match '/registro', to: 'users#new', via: 'get'
  match '/ingreso', to: 'sessions#new', via: 'get'
  match '/salir', to: 'sessions#destroy', via:'delete'
  match '/help', to: 'static_pages#help', via:'get' 
  match '/acerca_de', to: 'static_pages#acerca_de', via:'get'
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if ingresado?
  		@proyect = usuario_actual.proyects.build 
  		@feed_items = usuario_actual.feed.paginate(page: params[:page])
  	end
    session[:proyect_id] = nil
  end

  def help
  end

  def acerca_de
  end
  
  def contacto
  end

  def openii_proyect
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/acerca_de.html.erb
<% provide(:title, 'Acerca de') %>
<h1>Acerca de</h1>
<h2>
	<p>Openii es una aplicación desarrollada por Mario Omar Hernández para la 
	<a href="http://www.ute.edu.ec">Universidad Tecnológica Equinoccial</a> 
	como proyecto de tésis.</p>
<p>Ecuador - 2014</p>
</h2>

app/views/static_pages/contacto.html.erb
<% provide(:title, 'Contacto') %>
<h1>Contáctanos</h1>
<p>
<a href="http://www.ute.edu.ec/Default.aspx?idSeccion=206&idCategoria=220">Contáctanos</a>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Ayuda') %>
<h1>Ayuda</h1>
<p>Manual de ayuda</p>

app/views/static_pages/home.html.erb
<% if ingresado? %>
	<div class="row">
	    <aside class="span4">
	      <section>
	        <%= render 'shared/user_info' %>
	      </section>
	      <section>
	        <%= render 'shared/proyect_form' %>
	      </section>
	    </aside>
	    <div class="span8">
	      <h3>Proyectos</h3>
	      <%= render 'shared/feed' %>
	    </div>	    
	</div>
<% else %>
	<div class="center hero-unit">
		<h1>Bienvenido a Openii</h1>

		<h2>Este es un proyecto de la Facultad de Ingeniería de la <a href="http://www.ute.edu.ec">Universidad Tecnológica Equinoccial</a>
		</h2>
			<%= link_to "Regístrate", registro_path, class: "btn btn-large btn-primary" %>

	</div>

	<%= link_to image_tag("LOGO-UTE_color.gif", size: "80", alt: "Universidad Tecnológica Equinoccial"), 'http://www.ute.edu.ec' %>
<% end %>