config/routes.rb
Main::Application.routes.draw do
  resources :problemas
  resources :manoobras
  resources :metodos
  resources :maquinas
  resources :materials
  resources :medicions
  resources :medioambientes
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :proyects, only: [:create, :destroy]
  resources "contacts", only: [:new, :create]
  root 'static_pages#home'
  match '/seism', to: 'variables_entrada#seism', via: 'get'

  match '/openii_proyect', to: 'proyects#openii_proyect', via: 'get'
  match '/registro', to: 'users#new', via: 'get'
  match '/ingreso', to: 'sessions#new', via: 'get'
  match '/salir', to: 'sessions#destroy', via:'delete'
  match '/help', to: 'static_pages#help', via:'get' 
  match '/acerca_de', to: 'static_pages#acerca_de', via:'get'
  

end

app/models/problema.rb
class Problema < ActiveRecord::Base
	belongs_to :proyect
	validates 	:problema, 
				presence: true, 
				length: { maximum: 140 }, 
				uniqueness: { case_sensitive: false }
	validates 	:descripcion, 
				presence: true, 
				length: { maximum: 560 }
	validates 	:proyect_id, 
				presence: true
end

app/controllers/problemas_controller.rb
class ProblemasController < ApplicationController
  before_action :set_problema, only: [:show, :edit, :update, :destroy]
  before_action :usuario_ingresado, only: [:index, :edit, :update, :destroy]


  # GET /problemas
  # GET /problemas.json
  def index

    @problemas = proyecto_actual.problemas.paginate(page: params[:page])
  end

  # GET /problemas/1
  # GET /problemas/1.json
  def show
  end

  # GET /problemas/new
  def new
    @problema = Problema.new
  end

  # GET /problemas/1/edit
  def edit
  end

  # POST /problemas
  # POST /problemas.json
  def create
    @problema = proyecto_actual.problemas.build(problema_params)

    respond_to do |format|
      if @problema.save
        format.html { redirect_to @problema, notice: 'Problema was successfully created.' }
        format.json { render action: 'show', status: :created, location: @problema }
      else
        format.html { render action: 'new' }
        format.json { render json: @problema.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /problemas/1
  # PATCH/PUT /problemas/1.json
  def update
    respond_to do |format|
      if @problema.update(problema_params)
        format.html { redirect_to @problema, notice: 'Problema was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @problema.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problemas/1
  # DELETE /problemas/1.json
  def destroy
    @problema.destroy
    respond_to do |format|
      format.html { redirect_to problemas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_problema
      @problema = Problema.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def problema_params
      params.require(:problema).permit(:proyect_id, :problema, :descripcion)
    end




end

app/helpers/problemas_helper.rb
module ProblemasHelper
end

app/views/problemas/_form.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@problema) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :problema, "Problema" %>
    <%= f.text_field :problema %>

    <%= f.label :descripcion %>
    <%= f.text_area :descripcion, placeholder: "Descripción del problema" %>

    <%= f.submit "Guardar", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/problemas/_problema.html.erb
	<li>
		<span class="content"><%= problema.problema %></span>
		<%= link_to "editar", edit_problema_path(problema) %>
    	| <%= link_to "borrar", problema, method: :delete, data: { confirm: "Seguro?" } %>

	</li>

app/views/problemas/edit.html.erb
<%= render 'shared/openii_proyect_header' %>
<% provide(:title, 'Edita el problema') %>
<h3>Edita el problema</h3>

<%= render 'problemas/form' %>

app/views/problemas/index.html.erb
<%= render 'shared/openii_proyect_header' %>
<% provide(:title, 'Problemas') %>
<h3>Problemas</h3>

<%= will_paginate %>

<ul class="users">
  <%= render @problemas %>
</ul>

<%= will_paginate %>

app/views/problemas/new.html.erb
<%= render 'shared/openii_proyect_header' %>
<% provide(:title, 'Define un problema') %>
<h3>Define un problema</h3>

<%= render 'problemas/form' %>

app/views/problemas/show.html.erb
<%= render 'shared/openii_proyect_header' %>
<% provide(:title, @problema.problema) %>

<% provide(:title, 'Problemas') %>
<h3>Problema</h3>

<ul class="users">
  <%= render @problema %>
</ul>