config/routes.rb
Main::Application.routes.draw do
  resources :problemas
  resources :manoobras
  resources :metodos
  resources :maquinas
  resources :materials
  resources :medicions
  resources :medioambientes
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :proyects, only: [:create, :destroy]
  resources "contacts", only: [:new, :create]
  root 'static_pages#home'
  match '/seism', to: 'variables_entrada#seism', via: 'get'

  match '/openii_proyect', to: 'proyects#openii_proyect', via: 'get'
  match '/registro', to: 'users#new', via: 'get'
  match '/ingreso', to: 'sessions#new', via: 'get'
  match '/salir', to: 'sessions#destroy', via:'delete'
  match '/help', to: 'static_pages#help', via:'get' 
  match '/acerca_de', to: 'static_pages#acerca_de', via:'get'
  

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
	<div class="alert alert-error">
		La plantilla contiene <%= pluralize(object.errors.count, "error") %>
	</div>
	<ul>
		<% object.errors.full_messages.each do |msg| %>
		<li>* <%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="proyects">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= feed_item.nombre %></span>
  <span class="timestamp">
    Creado hace <%= time_ago_in_words(feed_item.created_at) %>.
  </span>
    <% if usuario_actual?(feed_item.user) %>
    <%= link_to "borrar", feed_item, method: :delete, data: { confirm: "Estas seguro?" }, title: feed_item.nombre %> | 
    <%= link_to "editar", openii_proyect_path(feed_item) %>

  	<% end %>
</li>

app/views/shared/_openii_proyect_header.html.erb
<div class="navbar-inner">
			Proyecto: <small><%= proyecto_actual.nombre %></small>
			<div class="container">
				 <div class="btn-group">

					<div class ="btn-group">
						<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Definición de problemas <span class="caret"></span></button>
						<ul class="dropdown-menu">
							<li><%= link_to "Nuevo", new_problema_path %></li>
							<li><%= link_to 'Ver problemas', problemas_path %></li>
						</ul>
					</div>

					<div class ="btn-group">
						<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Variables de entrada <span class="caret"></span></button>
						<ul class="dropdown-menu">
							<li><%= link_to "Metodología 6M", seism_path %></li>
							<li><a href="#">Flujo de procesos</a></li>
							<li><a href="#">Enumeración de causas</a></li>
						</ul>
					</div>

					<div class ="btn-group">
						<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Solución de problemas <span class="caret"></span></button>
						<ul class="dropdown-menu">
							<li><a href="#">Diagrama de causa efecto</a></li>
							<li><a href="#">Diagrama de Pareto</a></li>
							<li><a href="#">Diagrama de tendencia</a></li>
							<li><a href="#">Gráficas de control</a></li>
							<li><a href="#">Histograma</a></li>
							<li><a href="#">Diagrama de dispersión</a></li>
							<li><a href="#">Diagrama de Gantt</a></li>
						</ul>
					</div>

				</div>
			</div>
		</div>

app/views/shared/_proyect_form.html.erb
<%= form_for(@proyect) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :nombre, placeholder: "Título y descripción del proyecto" %>
  </div>
  <%= f.submit "Crear", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(usuario_actual, size: 52), usuario_actual %>
<h1>
  <%= usuario_actual.name %>
</h1>
<span>
  <%= link_to "Ver mi perfil.", usuario_actual %>
</span>
<span>
  <%= pluralize(usuario_actual.proyects.count, "proyect") %>
</span>