config/routes.rb
Main::Application.routes.draw do
  resources :problemas
  resources :manoobras
  resources :metodos
  resources :maquinas
  resources :materials
  resources :medicions
  resources :medioambientes
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :proyects, only: [:create, :destroy]
  resources "contacts", only: [:new, :create]
  root 'static_pages#home'
  match '/seism', to: 'variables_entrada#seism', via: 'get'

  match '/openii_proyect', to: 'proyects#openii_proyect', via: 'get'
  match '/registro', to: 'users#new', via: 'get'
  match '/ingreso', to: 'sessions#new', via: 'get'
  match '/salir', to: 'sessions#destroy', via:'delete'
  match '/help', to: 'static_pages#help', via:'get' 
  match '/acerca_de', to: 'static_pages#acerca_de', via:'get'
  

end

app/views/layouts/_footer.html.erb
<footer class "footer">
	<small>
		Producto de la Facultad de Ingeniería - <a href="http://www.ute.edu.ec">UTE</a>
	</small>
	<nav>
		<ul>
			<li><%= link_to "Acerca de", acerca_de_path %></li>
			<li><%= link_to "Contáctanos", new_contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
	<header class="navbar navbar-fixed-top navbar-inverse">
		<div class="navbar-inner">
			<div class="container">
				<%= link_to "Openii", root_path, id: "logo" %>
				<nav>
					<ul class="nav pull-right">
						<li><%= link_to "Inicio", root_path %></li>
						<li><%= link_to "Ayuda", help_path %></li>
						<% if ingresado? %>
							<li><%= link_to "Usuarios", users_path  %></li>
							<li id="fat-menu" class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= usuario_actual.name %><b class="caret"></b>
								</a>
								<ul class="dropdown-menu">
									<li><%= link_to "Perfil", usuario_actual %></li>
									<li><%= link_to "Preferencias", edit_user_path(usuario_actual) %> </li>
									<li class="divider"></li>
									<li>
										<%= link_to "Salir", salir_path, method: "delete" %>
									</li>
								</ul>
							</li>
						<% else %>
						<li><%= link_to "Ingresa", ingreso_path %></li>
						<% end %>
					</ul>
				</nav>
			</div>
		</div>
	</header>
	

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>

	<div class= "container">
		<% flash.each do |key, value| %>
			<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			
		<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>